- name: Create folder for JRE.
  file:
    path: "{{ globalFolder }}/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - java

- name: Download JRE.
  local_action:
    module: get_url
    url: "{{ javaUrl }}"
    dest: "temp/{{ javaPackage }}"
    mode: 0644
  run_once: True

- name: Unpack JRE.
  unarchive:
    src: "temp/{{ javaPackage }}"
    dest: "{{ globalFolder }}/java"
    extra_opts: [--strip-components=1]
    owner: "{{ user }}"
    group: "{{ user }}"